### PR TITLE
Minor fixes to resolve gsl error in integration for sigma_z0

### LINKED ISSUE #225: [BUG] GSL error when using Power spectrum in a lightcone
**Describe the bug:**
I am trying to run the code below for a lightcone with `POWER_SPECTRUM`= 5, I tried the same for a coeval box and it worked. Also, I ran a lightcone and coeval objects but with streaming velocities, which sets `POWER_SPECTRUM`= 5 and it worked. I tried running it from Jupyter Lab and also using a .py document in the terminal. 

**To Reproduce:**
`import py21cmfast as p21c` 
`from py21cmfast import plotting` 
`from py21cmfast import cache_tools` 
`import os` 
`print(f"21cmFAST version is {p21c.__version__}")` 

`lightcone = p21c.run_lightcone(` 
    `redshift = 5.0,` 
    `max_redshift = 15.0,` 
    `user_params = {"HII_DIM":256, "BOX_LEN": 400, "DIM":768, "POWER_SPECTRUM":5 },` 
    `lightcone_quantities=("brightness_temp", 'density', 'xH_box'),` 
    `global_quantities=("brightness_temp", 'density', 'xH_box'),` 
    `flag_options = {"INHOMO_RECO" : True,},` 
   `random_seed = 12345,` 
    `direc = 'lightconesf')` 

**Error showed:**
When I run the code I get this error, I will just show the part of it because it is too much text, between this it shows the cosmo, astro, user parameters. 
`2021-04-16 10:48:46 | ERROR   | ps.c            | sigma_z0:444 [pid=1808/thr=0] | gsl integration error occured!`
`2021-04-16 10:48:46 | ERROR   | ps.c            | sigma_z0:445 [pid=1808/thr=0] | (function argument): lower_limit=1.000000e-05 upper_limit=3.774746e+01 rel_tol=1.000000e-06 result=4.997059e+08 error=6.342499e+02`
`2021-04-16 10:48:46 | ERROR   | ps.c            | sigma_z0:446 [pid=1808/thr=0] | data: M=1.313924e+14`
.....
`Traceback (most recent call last):`
  `File "lps.py", line 9, in <module>`
    `lightcone = p21c.run_lightcone(`
  `File "/Users/catalinamorales/anaconda3/envs/myenv/lib/python3.8/site-packages/py21cmfast/wrapper.py", line 2753, in run_lightcone`
    `ib2 = ionize_box(`
  `File "/Users/catalinamorales/anaconda3/envs/myenv/lib/python3.8/site-packages/py21cmfast/wrapper.py", line 1637, in ionize_box`
    `return box.compute(`
  `File "/Users/catalinamorales/anaconda3/envs/myenv/lib/python3.8/site-packages/py21cmfast/_utils.py", line 1034, in compute`
    `_process_exitcode(exitcode, self._c_compute_function, args)`
  `File "/Users/catalinamorales/anaconda3/envs/myenv/lib/python3.8/site-packages/py21cmfast/_utils.py", line 116, in _process_exitcode`
   `raise {`
`py21cmfast._utils.GSLError: A GSL routine has errored! (check the LOG for more info)`

**Details:**
 - OS: macOS Big Sur 11.2.3
 - Python Version: 3.8.8
 - Relevant compiler versions: Jupyter lab: 3.0.9, GSL: 2.4
 - Relevant package versions: 21cmFAST version is 3.0.4.dev228+gec274c2

### PR DESCRIPTION
**Pull request by BradGreig**
Increase the accuracy of the GSL integration routine to resolve #225. May make the code ever so slightly slower, but should be negligible.

Additionally, update the error reporting for GSL errors to report the inbuilt GSL status code. This uses the already defined function that clearly I missed...

### CODE REVIEW

**Review by qyx268 — APPROVED** [review]
key 1 to key 6 looks like a huge increase... do you think it worth testing the time difference?

**Comment by BradGreig** [comment]
@qyx268 I'm not sure what you are referring to. What do you mean?

**Comment by qyx268** [comment]
I meant to test how much more time the change leads to for a typical run... I couldn't find the time difference for one gsl_integration_qag calculation on google easily... 

 GSL_INTEG_GAUSS15(key = 1)
 GSL_INTEG_GAUSS61(key = 6)

**Comment by BradGreig** [comment]
@qyx268 oh, no it's not that significant. It's only a few percent or more at most. It's not a big issue. Especially on decent sized boxes.

**Comment by qyx268** [comment]
ok

**Pull request merged**
