### PR TITLE
Release v3.1.2

### PR DESCRIPTION
**Pull request by steven-murray**
### Internals

* ``MINIMIZE_MEMORY`` flag significantly reduces memory without affecting performance much,
  by changing the way some arrays are allocated and accessed in C (#224)

### CODE REVIEW

**Comment by steven-murray** [comment]
@BradGreig this should essentially just be your PR getting released. Main things to check are that I got the CHANGELOG description right, and that you agree with bumping to 3.1.2 instead of 3.2.0

**Review by BradGreig — APPROVED** [review]
This all looks good to me.

Can we perhaps update the default behaviour of USE_INTERPOLATION_TABLES to be True in this same release? I don't see why this would be a problem with anything. Also it'll avoid more people running into these problems.

**Comment by steven-murray** [comment]
Yeah good idea. I'll try do that tomorrow.

**Comment by andreimesinger** [comment]
i agree with this

**Pull request merged**
